CREATE TABLE vicidial_uk_region_codes (
region VARCHAR(50) NOT NULL,
region_code VARCHAR(3) NOT NULL,
post_code_prefix VARCHAR(4) NOT NULL,
country_code VARCHAR(3) NOT NULL,
list_code_id VARCHAR(4),
index(post_code_prefix)
);

INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','CT','UKE','101');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','ME','UKE','101');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','TN','UKE','101');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','BN','UKE','102');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','GU','UKE','102');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','PO','UKE','102');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','RH','UKE','102');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO30','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO31','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO32','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO33','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO34','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO35','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO36','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO37','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO38','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO39','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO40','UKE','103');
INSERT INTO vicidial_uk_region_codes values('ISLE OF WHITE','IOW','PO41','UKE','103');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','BR','UKE','110');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','DA','UKE','110');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','SE','UKE','110');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','CR','UKE','111');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','KT','UKE','111');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','SM','UKE','111');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','SW','UKE','111');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','TW','UKE','111');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','EN','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','HA','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','NW','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N1','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N2','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N3','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N4','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N5','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N6','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N7','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N8','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','N9','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','UB','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','WC','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','WD','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W1','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W10','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W11','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W12','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W13','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W14','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W2','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W3','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W4','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W5','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W6','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W7','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W8','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','W9','UKE','112');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','EC','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E1','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E2','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E3','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E4','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E5','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E6','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E7','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E8','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','E9','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','IG','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','RM','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','SS','UKE','113');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','PL','UKE','201');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','TR','UKE','201');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','EX','EX','UKE','202');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','TQ','TQ','UKE','202');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','BA','UKE','203');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','BS','UKE','203');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','TA','UKE','203');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','SO','UKE','204');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','BH','UKE','204');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','DT','UKE','204');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','SP','UKE','204');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','OX','UKE','205');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','RG','UKE','205');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','SL','UKE','205');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','GL','UKE','206');
INSERT INTO vicidial_uk_region_codes values('SOUTH WEST','SW','SN','UKE','206');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','LU','UKE','301');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','MK','UKE','301');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','SG','UKE','301');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','AL','UKE','301');
INSERT INTO vicidial_uk_region_codes values('SOUTH EAST','SE','HP','UKE','301');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','CM','UKE','302');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','CO','UKE','302');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','NR','UKE','303');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','CB','UKE','304');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','PE','UKE','304');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','LE','UKE','305');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','NN','UKE','305');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','CV','UKE','305');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','DE','UKE','306');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','NG','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S1','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S2','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S3','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S4','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S5','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S6','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S7','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S8','UKE','306');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','S9','UKE','306');
INSERT INTO vicidial_uk_region_codes values('EAST MIDLANDS','EM','IP','UKE','313');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B1','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B11','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B2','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B3','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B4','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B5','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B6','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B7','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B8','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','B9','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','DY','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','WR','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','WS','UKE','401');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','WV','UKE','401');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','DN','UKE','501');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','LN','UKE','501');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','HU','UKE','502');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','YO','UKE','502');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','HG','UKE','503');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','LS','UKE','503');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','WF','UKE','503');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','DH','UKE','504');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','DL','UKE','504');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','NE','UKE','504');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','SR','UKE','504');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','TS','UKE','504');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','HD','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','BL','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','HX','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M1','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M2','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M3','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M4','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M5','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M6','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M7','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M8','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','M9','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','OL','UKE','601');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','FY','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L1','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L2','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L3','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L4','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L5','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L6','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L7','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L8','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','L9','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','PR','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','WA','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','WN','UKE','602');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CW','UKE','603');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','SK','UKE','603');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','ST','UKE','603');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','TF','UKE','603');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CA','UKE','604');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','LA','UKE','604');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','BB','UKE','605');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','BD','UKE','605');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','IM','UKI','606');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','CF','UKW','701');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','NP','UKW','701');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','SA','UKW','702');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','LD','UKW','703');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','HR','UKE','703');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','SY14','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','SY','UKW','704');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','SY15','UKW','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY1','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY10','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY11','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY12','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY13','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY2','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY3','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY4','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY5','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY6','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY7','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY8','UKE','704');
INSERT INTO vicidial_uk_region_codes values('WEST MIDLANDS','WM','SY9','UKE','704');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH1','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH2','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH3','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH4','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH44','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH45','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH60','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH61','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH62','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH63','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH64','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH65','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH66','UKE','705');
INSERT INTO vicidial_uk_region_codes values('NORTH WEST','NW','CH99','UKE','705');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','CH','UKW','705');
INSERT INTO vicidial_uk_region_codes values('WALES','WL','LL','UKW','705');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','EH','UKS','801');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','KY','UKS','801');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','FK','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G1','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G2','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G3','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G4','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G5','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G6','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G7','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G8','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','G9','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA1','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA10','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA11','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA12','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA13','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA14','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA15','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA16','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA17','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA18','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA19','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA2','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA3','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA4','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA5','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA6','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA7','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA8','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PA9','UKS','802');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','KA','UKS','803');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','ML','UKS','803');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','DD','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH1','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH10','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH11','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH12','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH13','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH14','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH15','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH16','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH2','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH3','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH4','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH5','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH6','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH7','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH8','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','PH9','UKS','804');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','DG','UKS','805');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','TD12','UKE','806');
INSERT INTO vicidial_uk_region_codes values('NORTH EAST','NE','TD15','UKE','806');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','TD','UKS','806');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','IV','UKS','807');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','AB','UKS','809');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','AB1','UKS','809');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','AB2','UKS','809');
INSERT INTO vicidial_uk_region_codes values('SCOTLAND','SC','AB3','UKS','809');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT1','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT10','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT2','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT3','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT4','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT5','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT6','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT7','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT8','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT0','BT9','UKN','901');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT11','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT12','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT13','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT14','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT15','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT16','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT17','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT18','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT19','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT1','BT20','UKN','902');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT21','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT22','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT23','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT24','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT25','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT26','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT27','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT28','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT29','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT30','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT31','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT32','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT33','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT34','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT2','BT35','UKN','903');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT36','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT37','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT38','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT39','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT40','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT41','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT42','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT43','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT44','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT45','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT3','BT46','UKN','904');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT47','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT48','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT49','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT50','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT51','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT52','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT53','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT54','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT55','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT56','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT4','BT57','UKN','905');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT58','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT59','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT60','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT61','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT62','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT63','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT64','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT65','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT66','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT67','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT68','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT69','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT70','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT5','BT71','UKN','906');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT72','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT73','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT74','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT75','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT76','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT77','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT78','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT79','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT80','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT81','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT82','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT83','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT84','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT85','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT86','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT87','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT88','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT89','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT90','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT91','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT92','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT93','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT94','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT95','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT96','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT97','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT98','UKN','907');
INSERT INTO vicidial_uk_region_codes values('NORTHERN IRELAND','BT7','BT99','UKN','907');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','GY','UKC','991');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','JE','UKC','991');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','TR21','UKE','992');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','TR22','UKE','992');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','TR23','UKE','992');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','TR24','UKE','992');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','TR25','UKE','992');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA20','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA21','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA22','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA23','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA24','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA25','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA26','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA27','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA28','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA29','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA30','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA31','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA32','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA33','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA34','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA35','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA36','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA37','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA38','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA39','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA40','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA41','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA42','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA43','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA44','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA45','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA46','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA47','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA48','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA49','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA60','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA61','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA62','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA63','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA64','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA65','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA66','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA67','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA68','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA69','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA70','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA71','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA72','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA73','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA74','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA75','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA76','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA77','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA78','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA80','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA81','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA82','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA83','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA84','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA85','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA86','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA87','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PA88','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH17','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH18','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH19','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH20','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH21','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH22','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH23','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH24','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH25','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH26','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH30','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH31','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH32','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH33','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH34','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH35','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH36','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH37','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH38','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH39','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH40','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH41','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH42','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH43','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','PH44','UKS','993');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','HS','UKS','994');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','KW','UKS','994');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','ZE','UKS','994');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','USA','USA','999');
INSERT INTO vicidial_uk_region_codes values('OUT OF AREA','OA','ZZ','FOR','999');
